#!/usr/bin/env python3
"""TEST-INFRA-ISOLATION-1: test-only launcher for `tests/test_websocket_e2e.py`.

Runs the **production entry point** `scripts/run_server.py` **exactly as
``__main__``** (same module-level bootstrap, same ``__main__`` block, same
event-loop policy, same app object, same uvicorn settings) — the *only*
difference is the bind address:

    production : 0.0.0.0:8000
    here       : 127.0.0.1:<argv[1]>   (ephemeral port chosen by the test)

Why a launcher instead of a port env-var/flag in `run_server.py`: this is a
**test-infrastructure** ticket — production files (`scripts/**`, `src/**`,
`configs/**`) must not change. This file is never imported by production code
and is **not collected by pytest** (its name does not match ``test_*.py`` /
``*_test.py``).

Port override is done by wrapping ``uvicorn.run`` before the production script
executes: `run_server.py` calls ``uvicorn.run(app, host=..., port=8000, ...)``
inside its ``__main__`` block, resolving the attribute at call time, so the
wrapper is what actually runs. The wrapper *replaces* host/port — it can never
fall through to the production bind address.

🔴 Identity handshake (why argv[2] exists)
------------------------------------------
On this machine `.venv\\Scripts\\python.exe` is a **uv trampoline (shim)**: the
pid returned by ``subprocess.Popen(...)`` is the *shim's* pid, while the real
interpreter running uvicorn is its **child** (measured: `Popen.pid=7088` vs
child self-report `12016`). So "uvicorn's logged pid == Popen.pid" is *not* a
valid identity test here.

Instead the first line this launcher writes to stderr is a **one-time nonce
handshake**:

    [TEST-INFRA-ISOLATION-1] launcher_pid=<os.getpid()> port=<port> nonce=<argv[2]>

The nonce is generated by the calling test and reaches us **only** through the
argv of the process the test spawned, so echoing it proves that this stderr
stream belongs to the process chain the test just started. The test then
additionally requires uvicorn's own `Started server process [<pid>]` to carry
the *same* pid, and its post-bind `Uvicorn running on ...:<port>` to carry the
test's port.

Isolation notes:
  * ``SOUL_OS_DATA_DIR`` is supplied by the calling test (a tmp dir) and
    inherited here, so the production ``data/`` tree is never written — in
    particular ``data/faulthandler.log`` (module level `open()`) lands in tmp.
  * ``stdout``/``stderr`` are redirected by the caller; the caller parses this
    process's stderr for the identity handshake above.

Usage:  python tests/_ws_e2e_server.py <port> <nonce>
"""
import os
import runpy
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

import uvicorn  # noqa: E402  (must be the same module object run_server.py imports)

if len(sys.argv) < 3:
    raise SystemExit("usage: _ws_e2e_server.py <port> <nonce>")

_TEST_PORT = int(sys.argv[1])
_TEST_NONCE = sys.argv[2]
_TEST_HOST = "127.0.0.1"

# Identity handshake: first line on stderr, flushed immediately.
print(
    f"[TEST-INFRA-ISOLATION-1] launcher_pid={os.getpid()} "
    f"port={_TEST_PORT} nonce={_TEST_NONCE}",
    file=sys.stderr,
    flush=True,
)

_real_uvicorn_run = uvicorn.run


def _run_on_isolated_test_address(app, *args, **kwargs):
    """Bind the production app to the isolated test address, and nothing else."""
    kwargs["host"] = _TEST_HOST
    kwargs["port"] = _TEST_PORT
    kwargs["reload"] = False
    return _real_uvicorn_run(app, *args, **kwargs)


uvicorn.run = _run_on_isolated_test_address

# Execute the production entry point verbatim, as __main__.
runpy.run_path(str(_ROOT / "scripts" / "run_server.py"), run_name="__main__")
