"""
src/conversation_qualification/qualifier.py — Conversation Qualification Boundary

M5.6-2 (Bry 派工 2026-08-10): First deterministic implementation.

This module implements the minimal ConversationQualification boundary that
decides whether a USER_MESSAGE-anchored conversation (closed via SESSION_END
when elapsed_mins >= 30) constitutes a meaningful lived experience worthy
of promotion to canonical InnerLifeEvent.

Key architectural rules (from M5.6-1 audit):

  R1  InnerLifeWriter is the SOLE creator of InnerLifeEvent.
  R2  Qualifier MUST NOT create InnerLifeEvent.
  R3  Qualifier MUST NOT call any other event-creation API.
  R4  Qualifier is READ-ONLY on conversation history.
  R5  Qualifier is READ-ONLY on existing signal sources.
  R6  Qualifier may only write to logs/observability.
  R7  On qualification, Qualifier calls InnerLifeWriter.create_event() with
      valid (NOT fabricated) provenance, session_id, correlation_id.
  R8  On non-qualification, Qualifier returns without action.
  R9  Qualifier failure (LLM timeout etc.) MUST NOT crash the bus;
      logger.warning + return None.
  R10 Qualifier is PER-SESSION (one decision per session close), not
      per-turn, not per-agent globally.

Privacy boundary (M5.6-1 Section 9):
  - v1 reads ONLY metadata (entry count, NOT content).
  - NO conversation text is read.
  - NO prompt / response text stored in qualification metadata.
  - Provenance.extras contains only numeric/categorical signals (durations,
    counts, IDs), NEVER raw text.

Identity boundary (M5.6-2 stop condition 5):
  - Per qualifying session, exactly ONE InnerLifeEvent is created.
  - event_id is generated by InnerLifeWriter (canonical), NEVER by
    Qualifier using uuid.uuid4() or any local generation.
  - session_id is taken from SESSION_END payload (last USER_MESSAGE
    session_id, NOT fabricated).
  - correlation_id = session_id (semantically: the session IS the
    narrative group for this conversation; no separate group marker).
  - parent_event_id = None (root event, lineage_depth=0).

Production safety:
  - READ-ONLY on data/conversations/, relationships.json, carryover, etc.
  - NO modification of memory.db / diary / dream / event / trace.
  - NO historical backfill.
  - NO replay.
  - Acts ONLY on future SESSION_END events.
"""
from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Any, Optional

from src.eventbus.schema import EventType, SoulEvent
from src.paths import data_root

if TYPE_CHECKING:
    from src.inner_life import InnerLifeWriter

logger = logging.getLogger("soul_os.conversation_qualification.qualifier")


# ─────────────────────────────────────────────────────────────────────
# v1 Qualification Policy Constants (Bry 派工 2026-08-10 拍板)
# ─────────────────────────────────────────────────────────────────────

# Minimum elapsed conversation duration in minutes for qualification.
# SESSION_END.payload.elapsed_mins >= this value triggers the duration check.
QUALIFICATION_DURATION_THRESHOLD_MINS: float = 5.0

# Minimum turn depth (entry count) in conversation history for qualification.
# data/conversations/{user}_{agent}_private.json entry count >= this triggers
# the turn_depth check.
QUALIFICATION_TURN_DEPTH_THRESHOLD: int = 4

# New Provenance.trigger_type value (additive to existing TRIGGER_TYPE_*).
# Per M5.6-1 Section 7.3: uses "narrative" as source_system (existing),
# trigger_type is a free-form string field in Provenance (no enum to alter).
TRIGGER_TYPE_CONVERSATION_USER_MESSAGE: str = "conversation:user_message"


# ─────────────────────────────────────────────────────────────────────
# Output: minimum schema (4 fields, per M5.6-1 Section 8.2)
# ─────────────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class ConversationQualificationResult:
    """Output of ConversationQualification.evaluate().

    Minimum output: just enough to call InnerLifeWriter.create_event() if
    qualified, and to log the decision regardless.

    Per M5.6-1 Section 8.1:
      - qualified: bool (the decision)
      - session_id: str (required for create_event + observability)
      - correlation_id: Optional[str] (required for create_event, may be None)
      - reason: str (observability only, never a counter / score / signal dict)

    Rejected fields (per ticket: "Do not add fields unless justified"):
      - confidence: NOT used downstream; InnerLifeEvent has no confidence
      - signals: dict noise; reconstructable from session if needed
      - temporal_boundaries: session metadata already tracks start/end
    """
    qualified: bool
    session_id: Optional[str]
    correlation_id: Optional[str]
    reason: str


# ─────────────────────────────────────────────────────────────────────
# ConversationQualification boundary
# ─────────────────────────────────────────────────────────────────────

class ConversationQualification:
    """
    M5.6-2 deterministic ConversationQualification boundary.

    Subscribes to SESSION_END events (with M5.6-2 additive session identity
    fields in payload) and, when a session has closed, decides whether the
    USER_MESSAGE-anchored conversation was a meaningful lived experience.

    On qualification: calls InnerLifeWriter.create_event() exactly once,
    with valid provenance. InnerLifeWriter is the SOLE creator.

    On rejection: returns without action. No event created.

    Privacy: v1 does NOT read conversation content. Only entry count.

    Lifecycle: must be registered with the bus via register() before events
    are dispatched. Optional — if not registered, no qualification happens
    and the rest of the system is unaffected (backward compatible).
    """

    SUBSCRIBER_ID = "conversation_qualification"

    def __init__(self, inner_life_writer: "InnerLifeWriter") -> None:
        """
        Args:
            inner_life_writer: canonical identity authority. Required.
                              Qualifier only CALLS create_event on it;
                              never creates events locally.
        """
        if inner_life_writer is None:
            raise ValueError(
                "ConversationQualification requires a non-None InnerLifeWriter "
                "(per M5.6-2 R1 + R2: Qualifier MUST NOT create events; only "
                "delegate to the canonical authority)."
            )
        self._writer = inner_life_writer
        # Observability counters
        self._stats = {
            "session_end_seen": 0,
            "session_id_missing": 0,
            "agent_id_missing": 0,
            "user_id_missing": 0,
            "history_missing": 0,
            "history_corrupt": 0,
            "qualified": 0,
            "rejected_duration": 0,
            "rejected_turn_depth": 0,
            "rejected_both": 0,
            "promoted_events": 0,
            "promotion_failures": 0,
        }

    # ── Lifecycle ─────────────────────────────────────────────

    def register(self, bus: Any) -> None:
        """
        Subscribe to SESSION_END events on the given bus.

        Should be called ONCE during lifespan setup, after InnerLifeWriter
        is created. NOT idempotent — re-registering would add a duplicate
        subscriber (bus.subscribe just appends; M5.7-3 audit finding P3.1).
        In production, register() is called once per
        ConversationQualification instance, in run_server.py lifespan.
        """
        bus.subscribe(
            subscriber_id=self.SUBSCRIBER_ID,
            handler=self.on_session_end,
            event_filter={EventType.SESSION_END},
        )
        logger.info(
            f"[ConversationQualification] 已訂閱 SESSION_END ✓ (v1 policy: "
            f"duration>={QUALIFICATION_DURATION_THRESHOLD_MINS}min AND "
            f"turn_depth>={QUALIFICATION_TURN_DEPTH_THRESHOLD})"
        )

    # ── Main handler ──────────────────────────────────────────

    async def on_session_end(self, event: SoulEvent) -> None:
        """
        SESSION_END handler. Per M5.6-2 stop condition 9, this MUST NOT crash
        the bus — all exceptions are caught and logged.

        Per M5.7-2 (Bry 派工 2026-08-10): when SESSION_END is received via bus
        (the production path through Heartbeat Engine), this handler MUST
        call promote() to actually create the InnerLifeEvent. The previous
        implementation only logged and incremented stats without calling
        promote(), which would cause the bus path to silently do nothing.
        """
        try:
            self._stats["session_end_seen"] += 1
            result = self.evaluate(event)
            if result.qualified:
                # M5.7-2: actual promotion — call writer.create_event()
                event_id = self.promote(result)
                if event_id is not None:
                    self._stats["qualified"] += 1
                    self._stats["promoted_events"] += 1
                    logger.info(
                        f"[ConversationQualification] PROMOTED session="
                        f"{result.session_id} → event_id={event_id[:12]}... "
                        f"reason={result.reason}"
                    )
                else:
                    self._stats["promotion_failures"] += 1
                    logger.warning(
                        f"[ConversationQualification] promote() returned None "
                        f"for session={result.session_id} (writer.create_event failed)"
                    )
            else:
                logger.debug(
                    f"[ConversationQualification] SKIPPED session="
                    f"{result.session_id} reason={result.reason}"
                )
        except Exception as e:
            # M5.6-2 R9: failure isolation — never crash the bus
            self._stats["promotion_failures"] += 1
            logger.warning(
                f"[ConversationQualification] handler 異常, 不影響主路徑: "
                f"{type(e).__name__}: {e}"
            )

    # ── Pure evaluation (testable) ────────────────────────────

    def evaluate(self, event: SoulEvent) -> ConversationQualificationResult:
        """
        Pure evaluation: extract session identity from SESSION_END payload,
        apply v1 qualification policy, return decision. No side effects.

        Per M5.6-2:
          - InnerLifeWriter is NOT called here.
          - Conversation history is read (READ-ONLY).
          - No content inspection (only entry count).

        This method is the source of truth for the v1 policy. Tests target it
        directly without needing to wire InnerLifeWriter.
        """
        payload = event.payload or {}

        # M5.6-2 Phase 1: extract session identity from SESSION_END payload.
        # These fields are ADDITIVE optional — set by HeartbeatEngine in M5.6-2
        # from the most recent USER_MESSAGE. If missing, we can't identify
        # the session → reject (graceful degradation).
        session_id = payload.get("last_session_id")
        user_id = payload.get("last_user_id")
        agent_id = payload.get("last_agent_id")

        if not session_id:
            self._stats["session_id_missing"] += 1
            return ConversationQualificationResult(
                qualified=False,
                session_id=None,
                correlation_id=None,
                reason="session_id_missing_in_payload",
            )
        if not user_id:
            self._stats["user_id_missing"] += 1
            return ConversationQualificationResult(
                qualified=False,
                session_id=session_id,
                correlation_id=None,
                reason="user_id_missing_in_payload",
            )
        if not agent_id:
            self._stats["agent_id_missing"] += 1
            return ConversationQualificationResult(
                qualified=False,
                session_id=session_id,
                correlation_id=None,
                reason="agent_id_missing_in_payload (group mode not supported in v1)",
            )

        # M5.6-2 privacy: read ONLY entry count, NOT content.
        # No text from user/assistant messages is read or stored.
        try:
            turn_depth = self._count_conversation_entries(user_id, agent_id)
        except FileNotFoundError:
            self._stats["history_missing"] += 1
            return ConversationQualificationResult(
                qualified=False,
                session_id=session_id,
                correlation_id=None,
                reason="conversation_history_file_missing",
            )
        except (json.JSONDecodeError, ValueError, KeyError) as e:
            self._stats["history_corrupt"] += 1
            return ConversationQualificationResult(
                qualified=False,
                session_id=session_id,
                correlation_id=None,
                reason=f"conversation_history_corrupt: {type(e).__name__}",
            )

        # Apply v1 qualification policy (deterministic, no LLM, no score).
        elapsed_mins = float(payload.get("elapsed_mins", 0.0))
        duration_ok = elapsed_mins >= QUALIFICATION_DURATION_THRESHOLD_MINS
        turn_depth_ok = turn_depth >= QUALIFICATION_TURN_DEPTH_THRESHOLD

        if duration_ok and turn_depth_ok:
            # QUALIFIED — promote to canonical InnerLifeEvent
            return ConversationQualificationResult(
                qualified=True,
                session_id=session_id,
                # M5.6-2 R7: correlation_id = session_id (semantically: the
                # session IS the narrative group for this conversation).
                # NOT fabricated — this is the same session_id from upstream.
                correlation_id=session_id,
                reason=(
                    f"duration={elapsed_mins:.1f}min>="
                    f"{QUALIFICATION_DURATION_THRESHOLD_MINS} AND "
                    f"turn_depth={turn_depth}>="
                    f"{QUALIFICATION_TURN_DEPTH_THRESHOLD}"
                ),
            )

        # REJECTED — record which threshold failed for observability
        if not duration_ok and not turn_depth_ok:
            self._stats["rejected_both"] += 1
            reason = (
                f"duration={elapsed_mins:.1f}min<"
                f"{QUALIFICATION_DURATION_THRESHOLD_MINS} AND "
                f"turn_depth={turn_depth}<{QUALIFICATION_TURN_DEPTH_THRESHOLD}"
            )
        elif not duration_ok:
            self._stats["rejected_duration"] += 1
            reason = (
                f"duration={elapsed_mins:.1f}min<"
                f"{QUALIFICATION_DURATION_THRESHOLD_MINS}"
            )
        else:
            self._stats["rejected_turn_depth"] += 1
            reason = (
                f"turn_depth={turn_depth}<{QUALIFICATION_TURN_DEPTH_THRESHOLD}"
            )

        return ConversationQualificationResult(
            qualified=False,
            session_id=session_id,
            correlation_id=None,
            reason=reason,
        )

    # ── Side-effect entry: caller invokes after evaluate() returns True ─

    def promote(self, result: ConversationQualificationResult) -> Optional[str]:
        """
        On qualified=True, call InnerLifeWriter.create_event() exactly once.

        Per M5.6-2 R7: uses valid (NOT fabricated) provenance, session_id,
        correlation_id from the upstream SESSION_END payload. The event_id
        is generated by InnerLifeWriter (canonical authority).

        Returns the canonical event_id on success, None on failure.

        This is the ONLY place where Qualifier creates side effects.
        """
        if not result.qualified:
            logger.warning(
                f"[ConversationQualification] promote() called on non-qualified "
                f"result, ignored. session={result.session_id}"
            )
            return None
        if not result.session_id or not result.correlation_id:
            logger.warning(
                f"[ConversationQualification] promote() missing identity, "
                f"ignored. session={result.session_id} corr={result.correlation_id}"
            )
            return None

        # Late import to avoid circular dependency at module load.
        # InnerLifeWriter is the canonical authority; we just call it.
        from src.inner_life import Provenance

        # Provenance.extras contains ONLY numeric/categorical signals, NEVER
        # raw text. Per M5.6-1 Section 9 privacy boundary.
        try:
            event = self._writer.create_event(
                provenance=Provenance(
                    trigger_type=TRIGGER_TYPE_CONVERSATION_USER_MESSAGE,
                    actor_id=result.session_id,  # session_id encodes user_id
                    source_system="narrative",  # existing, no enum change
                    extras={
                        "qualification_reason": result.reason,
                        # Numeric / categorical only — no raw text
                    },
                ),
                session_id=result.session_id,
                correlation_id=result.correlation_id,
                parent_event_id=None,  # root event, lineage_depth=0
            )
            logger.info(
                f"[ConversationQualification] InnerLifeWriter.create_event ✓ "
                f"event_id={event.event_id} session={result.session_id}"
            )
            return event.event_id
        except Exception as e:
            self._stats["promotion_failures"] += 1
            logger.warning(
                f"[ConversationQualification] InnerLifeWriter.create_event "
                f"失敗, 不影響主路徑: {type(e).__name__}: {e}"
            )
            return None

    # ── Conversation history reader (READ-ONLY, count only) ─

    def _count_conversation_entries(self, user_id: str, agent_id: str) -> int:
        """
        Read conversation history entry count. READ-ONLY.

        Per M5.6-1 privacy boundary: only COUNT is read. NO content is
        read, stored, or returned. The file is opened, the JSON list is
        parsed, len() is taken, and the file is closed. Content bytes
        are not retained.

        Path convention (per LLMProxy._group_path):
            data/conversations/{user_id}_{agent_id}_private.json

        Args:
            user_id: from SESSION_END payload (NOT fabricated)
            agent_id: from SESSION_END payload (NOT fabricated)

        Returns:
            int: number of entries in the conversation history.

        Raises:
            FileNotFoundError: if the history file doesn't exist
            json.JSONDecodeError: if the file is not valid JSON
            ValueError: if the file is not a list
        """
        path = self._conversation_path(user_id, agent_id)
        if not path.exists():
            raise FileNotFoundError(f"conversation history not found: {path}")
        # READ: parse JSON, take len(), discard content
        with path.open("r", encoding="utf-8") as f:
            data = json.load(f)
        if not isinstance(data, list):
            raise ValueError(
                f"conversation history is not a JSON list: {type(data).__name__}"
            )
        # M5.6-2 privacy: only count, do not retain content
        return len(data)

    @staticmethod
    def _conversation_path(user_id: str, agent_id: str) -> Path:
        """Resolve conversation history file path.

        Same convention as src/llm/proxy.py:_group_path:
            data/conversations/{user_id}_{agent_id}_private.json
        """
        return data_root() / "conversations" / f"{user_id}_{agent_id}_private.json"

    # ── Observability ──────────────────────────────────────────

    def get_stats(self) -> dict:
        """Return observability counters (READ-ONLY dict)."""
        return dict(self._stats)
